### PR TITLE
Add manual install instructions for ubuntu.

### PR DESCRIPTION
**Pull request by afaur**
Needed `dotties` on a `ubuntu vagrant box`, and thought I would share the steps I took. 

This is a WIP since it looks like some `dotties` functionality is not currently working inside ubuntu.

### CODE REVIEW

**Comment by afaur** [comment]
Slight issue with `.dotties.postup`
- When I install `dotties` on `ubuntu` it errors on the last command.
```
➜  / dotties uninstall afaur/dotties
Searching for invalid plugins in /root/.vim/plugged                                                   |
[==================]                                                                                  |~
Package 'afaur/dotties' uninstalled.
➜  / dotties install afaur/dotties
Cloning into '/root/.dotties/packages/afaur-dotties'...
remote: Counting objects: 120, done.
remote: Compressing objects: 100% (29/29), done.
remote: Total 120 (delta 14), reused 0 (delta 0), pack-reused 91
Receiving objects: 100% (120/120), 1.39 MiB | 767.00 KiB/s, done.
Resolving deltas: 100% (58/58), done.
Checking connectivity... done.
Cloning into '/root/.dotties/packages/tinytacoteam-dotties-mouse'...
remote: Counting objects: 8, done.
remote: Total 8 (delta 0), reused 0 (delta 0), pack-reused 8
Unpacking objects: 100% (8/8), done.
Checking connectivity... done.
Cloning into '/root/.dotties/packages/tinytacoteam-dotties-javascript'...
remote: Counting objects: 11, done.
remote: Total 11 (delta 0), reused 0 (delta 0), pack-reused 11
Unpacking objects: 100% (11/11), done.
Checking connectivity... done.
Cloning into '/root/.dotties/packages/tinytacoteam-dotties-vim'...
remote: Counting objects: 19, done.
remote: Total 19 (delta 0), reused 0 (delta 0), pack-reused 19
Unpacking objects: 100% (19/19), done.
Checking connectivity... done.
Package 'tinytacoteam/dotties-vim' already installed.
Cloning into '/root/.dotties/packages/tinytacoteam-dotties-git'...
remote: Counting objects: 25, done.
remote: Total 25 (delta 0), reused 0 (delta 0), pack-reused 25
Unpacking objects: 100% (25/25), done.
Checking connectivity... done.
Cloning into '/root/.dotties/packages/tinytacoteam-dotties-vim-movements'...
remote: Counting objects: 18, done.
remote: Total 18 (delta 0), reused 0 (delta 0), pack-reused 18
Unpacking objects: 100% (18/18), done.
Checking connectivity... done.
Cloning into '/root/.dotties/packages/tinytacoteam-dotties-tmux-movements'...
remote: Counting objects: 22, done.
remote: Total 22 (delta 0), reused 0 (delta 0), pack-reused 22
Unpacking objects: 100% (22/22), done.
Checking connectivity... done.
/root/.dotties.postup: 2: /root/.dotties.postup: source: not found
Package 'afaur/dotties' installed.
➜  / cat /root/.dotties.postup

        [ -f /root/.dotties/packages/tinytacoteam-dotties-vim/dotties.postup ] && source /root/.dotties/packages/tinytacoteam-dotties-vim/dotties.postup
      #                                                                                                                                                                                                    

```

If I run `source` afterwards ( the command `source /root/.dotties.postup` )  it seems like it finishes because it will start installing my vim plugins.

**Comment by amjith** [comment]
I'm surprised that you're having problems in Ubuntu. I was able to get it working as is on my Ubuntu machine. But it wasn't as root and it wasn't inside Vagrant either.

**Comment by afaur** [comment]
Thats interesting.  This is also ubuntu server instead of desktop now that I think about it.  I am thinking that its not using bash for that part of the dotties install (see http://unix.stackexchange.com/questions/225445/how-to-execute-source-command-from-sh-file) everything works if I run that '.dotties.postup' script inside my current bash shell.

**Comment by amjith** [comment]
Actually I do vaguely remember having the postup problem. I has something to do with Ubuntu using dash instead of bash for default shell. 

I thought I had fixed it in my fork, let me take a look.

**Comment by amjith** [comment]
I had to change this [file](https://github.com/tinytacoteam/dotties-core/blob/master/lib/dotties-core/formats/zshrc.rb#L5) to include `#!/bin/bash` on the top and something else too. Let me boot into my Ubuntu image and see what changes were made to make it work.

**Comment by amjith** [comment]
Oh crap! I didn't realize I had commit privileges to this repo, I accidentally pushed my changes straight to master. Let me revert that and make a PR.

**Pull request merged**
